### ISSUE TITLE
Can't read from & save to template from angular-eslint/angular-eslint

### ISSUE THREAD

**Issue by jerone** [mflorence99/lintel#23] opened 2020-11-06 17:53 UTC
I followed the instructions from [angular-eslint/angular-eslint](https://github.com/angular-eslint/angular-eslint) to install the necessary ESLint configuration with TypeScript & Angular support. After that I activated this VS extension, but got the "_Lintel could not start. Please try again._" error.

After stripping the `.eslintrc.json` file, I noticed that removing all comments allowed Intel to finally open. Reading the readme I saw that comments should be allowed:

> Lintel will preserve any comments you have placed in JSON, YAML or JavaScript configuration files. 

Then, after playing around with Lintel, I noticed that none of the configurations were saved back to the config file.

---

<details>
<summary>My config file looks like this...</summary>

```json
{
	"root": true,
	"overrides": [
		{
			"files": ["*.ts"],
			"parserOptions": {
				"project": ["tsconfig.*?.json"],
				"createDefaultProgram": true
			},
			"extends": [
				"plugin:@angular-eslint/recommended",
				"prettier/@typescript-eslint",
				"plugin:prettier/recommended"
			],
			"rules": {
				"max-len": ["error", { "code": 140, "ignoreUrls": true }]
			}
		},
		{
			"files": ["*.component.html"],
			"extends": ["plugin:@angular-eslint/template/recommended"],
			"rules": {
				"@angular-eslint/template/no-autofocus": "error",
				"@angular-eslint/template/no-positive-tabindex": "error"
			}
		},
		{
			"files": ["*.component.ts"],
			"extends": ["plugin:@angular-eslint/template/process-inline-templates"]
		}
	]
}
```

</details>

I'm running the latest of ESLint, VSCode and Lintel.

**Comment by jerone** [comment] 2020-11-06 19:04
The second issue above, looks like a Windows path issue. Similar to #14. Looking at the logs I see the following errors:

```
[2020-11-06 19:07:17.174] [renderer1] [error] ENOENT: no such file or directory, open 'c:Usersjeronesource
eposFrontendClientApp.eslintrc.json': Error: ENOENT: no such file or directory, open 'c:Usersjeronesource
eposFrontendClientApp.eslintrc.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at Timeout._onTimeout (c:\Users\jerone\.vscode\extensions\mflo999.lintel-1.3.0\ext\message-handler.ts:21:10)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
[2020-11-06 19:07:48.721] [renderer1] [error] cannot open c:Usersjeronesource%0DeposFrontendClientApp.eslintrc.json. Detail: Unable to resolve resource c:Usersjeronesource%0DeposFrontendClientApp.eslintrc.json: Error: cannot open c:Usersjeronesource%0DeposFrontendClientApp.eslintrc.json. Detail: Unable to resolve resource c:Usersjeronesource%0DeposFrontendClientApp.eslintrc.json
    at file:///C:/Users/jerone/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6688:388
```

**Comment by mflorence99** [comment] 2020-11-06 19:19
Many thanks for your bug report @jerone and your interest in Lintel! I'll take a look ASAP and report back.

**Comment by mflorence99** [comment] 2020-11-07 11:30
@jerone is there any chance you can post your original `'eslintrc.json`, the one with all the comments before you stripped them? I ran with the version above, and then with some random comments inserted, but I couldn't reproduce what you observed. Still looking at the second issue, the save failure in Windows. Many thanks!

**Comment by jerone** [comment] 2020-11-07 11:46
Sorry, I'm away from my PC right now. I started with the default template from angular-eslint (see above).

**Comment by mflorence99** [comment] 2020-11-07 12:00
No hurry -- let's try both tacks if we can. I'll try to reconstruct while you post the original whenever convenient.

**Comment by jerone** [comment] 2020-11-07 14:44
Template file by angular-eslint/angular-eslint: https://github.com/angular-eslint/angular-eslint/blob/master/packages/schematics/src/add-config-to-project/files/root-files/.eslintrc.json__tmpl__

<details>
<summary>My config file...</summary>

```json
/**
 * -----------------------------------------------------
 * NOTES ON CONFIGURATION STRUCTURE
 * -----------------------------------------------------
 *
 * Out of the box, ESLint does not support TypeScript or HTML. Naturally those are the two
 * main file types we care about in Angular projects, so we have to do a little extra work
 * to configure ESLint exactly how we need to.
 *
 * Fortunately, ESLint gives us an "overrides" configuration option which allows us to set
 * different lint tooling (parser, plugins, rules etc) for different file types, which is
 * critical because our .ts files require a different parser and different rules to our
 * .html (and our inline Component) templates.
 */
{
	"root": true,
	"overrides": [
		/**
		 * -----------------------------------------------------
		 * TYPESCRIPT FILES (COMPONENTS, SERVICES ETC) (.ts)
		 * -----------------------------------------------------
		 * The `parser`-property is defined in `plugin:@angular-eslint/recommended`.
		 */
		{
			"files": ["*.ts"],
			"parserOptions": {
				"project": ["**/tsconfig.*?.json"],
				"createDefaultProgram": true
			},
			"extends": [
				// Uses the recommended rules for TypeScript and Angular.
				// https://github.com/angular-eslint/angular-eslint#rules-list
				// https://github.com/angular-eslint/angular-eslint/tree/master/packages/eslint-plugin/src/configs
				"plugin:@angular-eslint/recommended",

				// Uses eslint-config-prettier to disable ESLint rules that would conflict with prettier.
				"prettier/@typescript-eslint",

				// Enables eslint-plugin-prettier and eslint-config-prettier.
				// This will display prettier errors as ESLint errors.
				// Make sure this is always the last configuration in the extends array.
				"plugin:prettier/recommended"
			],
			"rules": {
				/**
				 * Any TypeScript related rules you wish to use/reconfigure over and above the
				 * recommended set provided by the @angular-eslint project would go here.
				 */

				// Prettier has `printWidth` set to a lower number, which is the preferred *readable* line length.
				// But Prettier doesn't enforce this on all lines, e.g. single imports.
				// This setting just ensures that we never have too long lines.
				"max-len": ["error", { "code": 140, "ignoreUrls": true }],

				// Require explicit accessibility modifiers on class properties and methods.
				"@typescript-eslint/explicit-member-accessibility": ["error"],

				// Disallows explicit type declarations on parameters, variables and properties.
				// TODO: find rule to enforce explicit type declarations.
				"@typescript-eslint/no-inferrable-types": ["off"],

				// Disallow the use of console.
				"no-console": ["warn", { "allow": ["error"] }],

				// Use generic array `Array<T>`.
				"@typescript-eslint/array-type": ["error", { "default": "generic" }],

				// TypeScript suggests never prefixing interfaces with "I".
				// https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names
				"@typescript-eslint/naming-convention": [
					"error",
					{
						"selector": "interface",
						"format": ["PascalCase"],
						"custom": {
							"regex": "^I[A-Z]",
							"match": false
						}
					}
				],

				// Only one class per file.
				"max-classes-per-file": ["error", 1],

				// Use TypeScript import syntax.
				"@typescript-eslint/no-var-requires": ["error"],

				// Use dot notation `foo.bar` over square-bracket notation `foo["bar"]`.
				"dot-notation": ["error"],

				// Disallow unused variables & declarations.
				"no-unused-vars": "off", // Disable the base rule as it can report incorrect errors.
				"@typescript-eslint/no-unused-vars": ["error"],

				// Remove useless constructor.
				"no-useless-constructor": "off", // Disable the base rule as it can report incorrect errors.
				"@typescript-eslint/no-useless-constructor": ["error"],

				// This rule enforces not using parameter properties.
				// Actually, this rule should be inversed and `private readonly` should be enforced.
				// But for now no parameter properties are allowed, but `private readonly` is preferred.
				// TODO: find solution to inverse this rule and enforce `private readonly`. See https://github.com/typescript-eslint/typescript-eslint/issues/103
				"@typescript-eslint/no-parameter-properties": [
					"error",
					{ "allows": ["private readonly"] }
				],

				// Disallow reassignment of parameters.
				"no-param-reassign": ["error"]

				// "@typescript-eslint/strict-boolean-expressions": ["error"]
			}
		},

		/**
		 * -----------------------------------------------------
		 * COMPONENT TEMPLATES
		 * -----------------------------------------------------
		 *
		 * If you use inline templates, make sure you read the notes on the configuration
		 * object after this one to understand how they relate to this configuration directly
		 * below.
		 */
		{
			"files": ["*.component.html"],
			"extends": [
				// HTML specific rules.
				// https://github.com/angular-eslint/angular-eslint/tree/master/packages/eslint-plugin-template/src/configs
				"plugin:@angular-eslint/template/recommended"
			],
			"rules": {
				// No `autofocus`-attribute in HTML.
				"@angular-eslint/template/no-autofocus": "error",

				// No positive `tabindex`-attribute in HTML.
				"@angular-eslint/template/no-positive-tabindex": "error"
			}
		},

		/**
		 * -----------------------------------------------------
		 * EXTRACT INLINE TEMPLATES (from within .component.ts)
		 * -----------------------------------------------------
		 *
		 * This extra piece of configuration is necessary to extract inline
		 * templates from within Component metadata, e.g.:
		 *
		 * @Component({
		 *  template: `<h1>Hello, World!</h1>`
		 * })
		 * ...
		 *
		 * It works by extracting the template part of the file and treating it as
		 * if it were a full .html file, and it will therefore match the configuration
		 * specific for *.component.html above when it comes to actual rules etc.
		 *
		 * NOTE: This processor will skip a lot of work when it runs if you don't use
		 * inline templates in your projects currently, so there is no great benefit
		 * in removing it, but you can if you want to.
		 *
		 * You won't specify any rules here. As noted above, the rules that are relevant
		 * to inline templates are the same as the ones defined for *.component.html.
		 */
		{
			"files": ["*.component.ts"],
			"extends": [
				// https://github.com/angular-eslint/angular-eslint/blob/master/packages/eslint-plugin-template/src/configs/process-inline-templates.json
				"plugin:@angular-eslint/template/process-inline-templates"
			]
		}
	]
}

```

</details>

**Comment by mflorence99** [comment] 2020-11-07 18:47
Many thanks @jerone -- I have your new `.eslintrc.json`. My first repro attempt failed but I have another plan. I confess our US election news will keep me consumed for a little while, but be assured I'll be working again on this ASAP.

**Comment by mflorence99** [comment] 2020-11-08 12:00
OK, can repro now.

**Comment by mflorence99** [comment] 2020-11-08 12:22
It was the embedded backticks in the `.eslintrc.json` file. They had to be escaped. Fix committed but before I release I will separate the Windows issue into a new ticket and address it.

**Comment by mflorence99** [comment] 2020-11-08 20:45
Just published v1.3.1 which should fix #23 and #25. #26 is a bit tricky and I have to think about it. I just wanted to get @jerone started in light of the fact I don't really have a Windows system. Should be available by 4pm US ET.

**Closed by mflorence99** 2020-11-08 20:45 UTC

**Comment by jerone** [comment] 2020-11-08 21:10
@mflorence99 Thanks for the quick response and solution. I'll definitely test this tomorrow.

**Comment by jerone** [comment] 2020-11-09 14:19
@mflorence99 I just had a moment to test this on Windows and I'm able to open Lintel 🎉 Great work on getting it working.

I do have some feedback during testing:

*   "_Edit other settings in .eslintrc.json_" doesn't do anything.

![](https://user-images.githubusercontent.com/55841/98549356-f5dad780-229a-11eb-9286-20bedadd9a14.png)

*   It adds an empty `"rules": {}` property at the root when changing one of the overrides.
*   All the settings (not the ESLint rules, but like `ecmaFeatures`, etc...) are saved correctly to the config file (both root and overrides), but once reloaded/reopened not correctly shown in Lintel. E.g. all the checked features are unchecked in Lintel. But that's probably #26.
*   I use Prettier. Any change to format the config json according to Prettier, as a setting?
*   Any change to recognize the rules from (new issue?):
    *   @typescript-eslint ➡ https://github.com/typescript-eslint/typescript-eslint/tree/master/packages/eslint-plugin#supported-rules
    *   @angular-eslint ➡ https://github.com/angular-eslint/angular-eslint#rules-list
    *   Prettier ➡ https://github.com/prettier/eslint-config-prettier (aldo this package only turns off all rules that are unnecessary or might conflict with [Prettier](https://github.com/prettier/prettier)).

**Comment by mflorence99** [comment] 2020-11-09 14:39
Many thanks for your interest and testing! Yes, you are running into #26 and I need to fix that first.

Regarding "edit other settings" ... I guess that must be another windows thing. I can't repro that. It opens a column alongside Lintel for me. I'll check that out, but I need to fix #26 first.

Thanks again!

**Comment by jerone** [comment] 2020-11-09 15:30
> Regarding "edit other settings" ... I guess that must be another windows thing. I can't repro that. It opens a column alongside Lintel for me. 

It appears to be a Windows thing again from the log (should have included that):

```
[2020-11-09 16:27:09.068] [renderer1] [error] cannot open c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json. Detail: Unable to resolve resource c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json: Error: cannot open c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json. Detail: Unable to resolve resource c:%5CUsers%5Cjerone%5Csource%5Crepos%5CFrontend%5CClientApp%5C.eslintrc.json
    at file:///C:/Users/jerone/AppData/Local/Programs/Microsoft VS Code/resources/app/out/vs/workbench/workbench.desktop.main.js:6688:388
```

**Comment by jerone** [comment] 2020-11-09 16:16
I haven't build any VSCode extension (yet), but maybe VS can help:

*   https://stackoverflow.com/a/55660674/108448
*   https://code.visualstudio.com/api/references/vscode-api#Uri.file
*   https://code.visualstudio.com/api/references/vscode-api#Uri.fsPath
*   And otherwise, the good old fs & path might help:

```javascript
const fs = require("fs");
const path = require("path");
```

**Comment by mflorence99** [comment] 2020-11-09 20:24
Thanks -- I'm using those APIs -- there'll be something I missed of course otherwise you wouldn't have a problem!
